# Generated by Django 5.1.15 on 2026-03-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=99, help_text='数値が小さいほど優先度が高い (例: 1=最優先)', verbose_name='優先度'),
        ),
    ]
