# Generated by Django 5.1.15 on 2026-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='必須'),
        ),
        migrations.AddField(
            model_name='task',
            name='recommended_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='推奨実行日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', '未実行'), ('COMPLETED', '完了'), ('NOT_REQUIRED', '実施不要'), ('FAILED', '失敗（期限超過による消滅）')], default='PENDING', max_length=20, verbose_name='ステータス'),
        ),
    ]
